# Configurações do banco de dados
spring:
  datasource:
    url: jdbc:mysql://aws.connect.psdb.cloud:3306/walkerusers?sslMode=VERIFY_IDENTITY
    username: x2bm0uokt0ifjic7kgeu
    password: pscale_pw_LvEhWfZzGNzSXs06d180BONMc8p4yPSBub00CUiDeu2
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Configurações do Hibernate
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

# Configurações do log
logging:
  level:
    org.springframework: INFO
    com.example: DEBUG
