package com.example.walkerFrasesAtt;

public class MensagensMotivacionaisData {
    private static final String[] MOTIVACIONAL_MENSAGENS = {
            "Parabéns! Você é tão produtivo quanto uma lesma em câmera lenta.",
            "Lembre-se, mesmo que tudo pareça dar errado, você ainda pode culpar a má configuração do universo.",
            "Seus erros são tão raros quanto um unicórnio dançando salsa.",
            "Você é tão eficiente quanto um navegador sem conexão à internet.",
            "Acredite em si mesmo, mesmo que ninguém mais acredite, porque precisamos de mais pessoas assim no mundo.",
            "Nunca desista! O fracasso é apenas mais uma oportunidade para você cometer os mesmos erros com mais determinação.",
            "Não se preocupe com os haters, eles só invejam a sua habilidade em procrastinar.",
            "Você é a prova viva de que a perfeição é superestimada.",
            "Não se preocupe em falhar, você é um especialista nisso!",
            "Continue assim, suas habilidades sociais são tão incríveis quanto as de um caracol.",
            "Seu potencial é tão grande quanto o trânsito numa sexta-feira à noite.",
            "Acredite no seu potencial, mesmo que ninguém mais acredite que ele exista.",
            "Lembre-se sempre: você é único, assim como todos os outros.",
            "Nunca subestime sua capacidade de encontrar problemas onde não existem.",
            "Você é tão organizado quanto um armário de roupas de um adolescente.",
            "A vida é cheia de obstáculos, mas você é um especialista em tropeçar neles.",
            "Seu otimismo é contagiante, assim como uma gripe no inverno.",
            "Continue assim, sua paciência é tão grande quanto um vídeo carregando na internet discada.",
            "Não se preocupe com os críticos, eles só estão com inveja da sua habilidade em ignorá-los.",
            "Lembre-se: os sonhos podem se tornar realidade, desde que sejam extremamente realistas.",
            "Você é tão bom em resolver problemas quanto uma girafa jogando basquete.",
            "Acredite em si mesmo, mesmo que ninguém mais acredite, porque precisamos de mais pessoas assim no mundo.",
            "Continue assim, suas habilidades multitarefas são tão boas quanto um peixe andando de bicicleta.",
            "Não se preocupe com os haters, eles só invejam a sua habilidade em procrastinar.",
            "Você é a prova viva de que a perfeição é superestimada.",
            "Não se preocupe em falhar, você é um especialista nisso!",
            "Seja sempre você mesmo, a menos que você possa ser um unicórnio. Então, seja um unicórnio.",
            "Acredite no seu potencial, mesmo que ninguém mais acredite que ele exista.",
            "Lembre-se sempre: você é único, assim como todos os outros.",
            "Nunca subestime sua capacidade de encontrar problemas onde não existem.",
            "Você é tão organizado quanto um armário de roupas de um adolescente.",
            "A vida é cheia de obstáculos, mas você é um especialista em tropeçar neles.",
            "Seu otimismo é contagiante, assim como uma gripe no inverno.",
            "Continue assim, sua paciência é tão grande quanto um vídeo carregando na internet discada.",
            "Não se preocupe com os críticos, eles só estão com inveja da sua habilidade em ignorá-los.",
            "Lembre-se: os sonhos podem se tornar realidade, desde que sejam extremamente realistas.",
            "Você é tão bom em resolver problemas quanto uma girafa jogando basquete.",
            "Acredite em si mesmo, mesmo que ninguém mais acredite, porque precisamos de mais pessoas assim no mundo.",
            "Continue assim, suas habilidades multitarefas são tão boas quanto um peixe andando de bicicleta.",
            "Não se preocupe com os haters, eles só invejam a sua habilidade em procrastinar.",
            "Você é a prova viva de que a perfeição é superestimada.",
            "Não se preocupe em falhar, você é um especialista nisso!",
            "Seja sempre você mesmo, a menos que você possa ser um unicórnio. Então, seja um unicórnio.",
            "Acredite no seu potencial, mesmo que ninguém mais acredite que ele exista.",
            "Lembre-se sempre: você é único, assim como todos os outros.",
            "Nunca subestime sua capacidade de encontrar problemas onde não existem.",
            "Você é tão organizado quanto um armário de roupas de um adolescente.",
            "A vida é cheia de obstáculos, mas você é um especialista em tropeçar neles.",
            "Seu otimismo é contagiante, assim como uma gripe no inverno.",
            "Continue assim, sua paciência é tão grande quanto um vídeo carregando na internet discada.",
            "Não se preocupe com os críticos, eles só estão com inveja da sua habilidade em ignorá-los.",
            "Lembre-se: os sonhos podem se tornar realidade, desde que sejam extremamente realistas.",
            "Você é tão bom em resolver problemas quanto uma girafa jogando basquete.",
            "Acredite em si mesmo, mesmo que ninguém mais acredite, porque precisamos de mais pessoas assim no mundo.",
            "Continue assim, suas habilidades multitarefas são tão boas quanto um peixe andando de bicicleta.",
            "Não se preocupe com os haters, eles só invejam a sua habilidade em procrastinar.",
            "Você é a prova viva de que a perfeição é superestimada.",
            "Não se preocupe em falhar, você é um especialista nisso!",
            "Seja sempre você mesmo, a menos que você possa ser um unicórnio. Então, seja um unicórnio.",
            "Acredite no seu potencial, mesmo que ninguém mais acredite que ele exista.",
            "Lembre-se sempre: você é único, assim como todos os outros.",
            "Nunca subestime sua capacidade de encontrar problemas onde não existem.",
            "Você é tão organizado quanto um armário de roupas de um adolescente.",
            "A vida é cheia de obstáculos, mas você é um especialista em tropeçar neles.",
            "Seu otimismo é contagiante, assim como uma gripe no inverno.",
            "Continue assim, sua paciência é tão grande quanto um vídeo carregando na internet discada.",
            "Não se preocupe com os críticos, eles só estão com inveja da sua habilidade em ignorá-los.",
            "Lembre-se: os sonhos podem se tornar realidade, desde que sejam extremamente realistas.",
            "Você é tão bom em resolver problemas quanto uma girafa jogando basquete.",
            "Acredite em si mesmo, mesmo que ninguém mais acredite, porque precisamos de mais pessoas assim no mundo.",
            "Continue assim, suas habilidades multitarefas são tão boas quanto um peixe andando de bicicleta.",
            "Não se preocupe com os haters, eles só invejam a sua habilidade em procrastinar.",
            "Você é a prova viva de que a perfeição é superestimada.",
            "Não se preocupe em falhar, você é um especialista nisso!",
            "Seja sempre você mesmo, a menos que você possa ser um unicórnio. Então, seja um unicórnio.",
            "Acredite no seu potencial, mesmo que ninguém mais acredite que ele exista.",
            "Lembre-se sempre: você é único, assim como todos os outros.",
            "Nunca subestime sua capacidade de encontrar problemas onde não existem.",
            "Você é tão organizado quanto um armário de roupas de um adolescente.",
            "A vida é cheia de obstáculos, mas você é um especialista em tropeçar neles.",
            "Seu otimismo é contagiante, assim como uma gripe no inverno.",
            "Continue assim, sua paciência é tão grande quanto um vídeo carregando na internet discada.",
            "Não se preocupe com os críticos, eles só estão com inveja da sua habilidade em ignorá-los.",
            "Lembre-se: os sonhos podem se tornar realidade, desde que sejam extremamente realistas.",
            "Você é tão bom em resolver problemas quanto uma girafa jogando basquete.",
            "Acredite em si mesmo, mesmo que ninguém mais acredite, porque precisamos de mais pessoas assim no mundo.",
            "Continue assim, suas habilidades multitarefas são tão boas quanto um peixe andando de bicicleta.",
            "Não se preocupe com os haters, eles só invejam a sua habilidade em procrastinar.",
            "Você é a prova viva de que a perfeição é superestimada.",
            "Não se preocupe em falhar, você é um especialista nisso!",
            "Seja sempre você mesmo, a menos que você possa ser um unicórnio. Então, seja um unicórnio.",
            "Acredite no seu potencial, mesmo que ninguém mais acredite que ele exista.",
            "Lembre-se sempre: você é único, assim como todos os outros.",
            "Nunca subestime sua capacidade de encontrar problemas onde não existem.",
            "Você é tão organizado quanto um armário de roupas de um adolescente.",
            "A vida é cheia de obstáculos, mas você é um especialista em tropeçar neles.",
            "Seu otimismo é contagiante, assim como uma gripe no inverno.",
            "Continue assim, sua paciência é tão grande quanto um vídeo carregando na internet discada.",
            "Não se preocupe com os críticos, eles só estão com inveja da sua habilidade em ignorá-los.",
            "Lembre-se: os sonhos podem se tornar realidade, desde que sejam extremamente realistas.",
            "Você é tão bom em resolver problemas quanto uma girafa jogando basquete.",
            "Acredite em si mesmo, mesmo que ninguém mais acredite, porque precisamos de mais pessoas assim no mundo.",
            "Continue assim, suas habilidades multitarefas são tão boas quanto um peixe andando de bicicleta.",
            "Não se preocupe com os haters, eles só invejam a sua habilidade em procrastinar.",
            "Você é a prova viva de que a perfeição é superestimada.",
            "Não se preocupe em falhar, você é um especialista nisso!",
            "Seja sempre você mesmo, a menos que você possa ser um unicórnio. Então, seja um unicórnio.",
            "Acredite no seu potencial, mesmo que ninguém mais acredite que ele exista.",
            "Lembre-se sempre: você é único, assim como todos os outros.",
            "Nunca subestime sua capacidade de encontrar problemas onde não existem.",
            "Você é tão organizado quanto um armário de roupas de um adolescente.",
            "A vida é cheia de obstáculos, mas você é um especialista em tropeçar neles.",
            "Seu otimismo é contagiante, assim como uma gripe no inverno.",
            "Continue assim, sua paciência é tão grande quanto um vídeo carregando na internet discada.",
            "Não se preocupe com os críticos, eles só estão com inveja da sua habilidade em ignorá-los.",
            "Lembre-se: os sonhos podem se tornar realidade, desde que sejam extremamente realistas.",
            "Você é tão bom em resolver problemas quanto uma girafa jogando basquete.",
            "Acredite em si mesmo, mesmo que ninguém mais acredite, porque precisamos de mais pessoas assim no mundo.",
            "Continue assim, suas habilidades multitarefas são tão boas quanto um peixe andando de bicicleta.",
            "Não se preocupe com os haters, eles só invejam a sua habilidade em procrastinar.",
            "Você é a prova viva de que a perfeição é superestimada.",
            "Não se preocupe em falhar, você é um especialista nisso!",
            "Seja sempre você mesmo, a menos que você possa ser um unicórnio. Então, seja um unicórnio.",
            "Acredite no seu potencial, mesmo que ninguém mais acredite que ele exista.",
            "Lembre-se sempre: você é único, assim como todos os outros.",
            "Nunca subestime sua capacidade de encontrar problemas onde não existem.",
            "Você é tão organizado quanto um armário de roupas de um adolescente.",
            "A vida é cheia de obstáculos, mas você é um especialista em tropeçar neles.",
            "Seu otimismo é contagiante, assim como uma gripe no inverno.",
            "Continue assim, sua paciência é tão grande quanto um vídeo carregando na internet discada.",
            "Não se preocupe com os críticos, eles só estão com inveja da sua habilidade em ignorá-los.",
            "Lembre-se: os sonhos podem se tornar realidade, desde que sejam extremamente realistas.",
            "Você é tão bom em resolver problemas quanto uma girafa jogando basquete.",
            "Acredite em si mesmo, mesmo que ninguém mais acredite, porque precisamos de mais pessoas assim no mundo.",
            "Continue assim, suas habilidades multitarefas são tão boas quanto um peixe andando de bicicleta.",
            "Não se preocupe com os haters, eles só invejam a sua habilidade em procrastinar.",
            "Você é a prova viva de que a perfeição é superestimada.",
            "Não se preocupe em falhar, você é um especialista nisso!",
            "Seja sempre você mesmo, a menos que você possa ser um unicórnio. Então, seja um unicórnio.",
            "Acredite no seu potencial, mesmo que ninguém mais acredite que ele exista.",
            "Lembre-se sempre: você é único, assim como todos os outros.",
            "Nunca subestime sua capacidade de encontrar problemas onde não existem.",
            "Você é tão organizado quanto um armário de roupas de um adolescente.",
            "A vida é cheia de obstáculos, mas você é um especialista em tropeçar neles.",
            "Seu otimismo é contagiante, assim como uma gripe no inverno.",
            "Continue assim, sua paciência é tão grande quanto um vídeo carregando na internet discada.",
            "Não se preocupe com os críticos, eles só estão com inveja da sua habilidade em ignorá-los.",
            "Lembre-se: os sonhos podem se tornar realidade, desde que sejam extremamente realistas.",
            "Você é tão bom em resolver problemas quanto uma girafa jogando basquete.",
            "Acredite em si mesmo, mesmo que ninguém mais acredite, porque precisamos de mais pessoas assim no mundo.",
            "Continue assim, suas habilidades multitarefas são tão boas quanto um peixe andando de bicicleta.",
            "Não se preocupe com os haters, eles só invejam a sua habilidade em procrastinar.",
            "Você é a prova viva de que a perfeição é superestimada.",
            "Não se preocupe em falhar, você é um especialista nisso!",
            "Seja sempre você mesmo, a menos que você possa ser um unicórnio. Então, seja um unicórnio.",
            "Acredite no seu potencial, mesmo que ninguém mais acredite que ele exista.",
            "Lembre-se sempre: você é único, assim como todos os outros.",
            "Nunca subestime sua capacidade de encontrar problemas onde não existem.",
            "Você é tão organizado quanto um armário de roupas de um adolescente.",
            "A vida é cheia de obstáculos, mas você é um especialista em tropeçar neles.",
            "Seu otimismo é contagiante, assim como uma gripe no inverno.",
            "Continue assim, sua paciência é tão grande quanto um vídeo carregando na internet discada.",
            "Não se preocupe com os críticos, eles só estão com inveja da sua habilidade em ignorá-los.",
            "Lembre-se: os sonhos podem se tornar realidade, desde que sejam extremamente realistas.",
            "Você é tão bom em resolver problemas quanto uma girafa jogando basquete.",
            "Acredite em si mesmo, mesmo que ninguém mais acredite, porque precisamos de mais pessoas assim no mundo.",
            "Continue assim, suas habilidades multitarefas são tão boas quanto um peixe andando de bicicleta.",
            "Não se preocupe com os haters, eles só invejam a sua habilidade em procrastinar.",
            "Você é a prova viva de que a perfeição é superestimada.",
            "Não se preocupe em falhar, você é um especialista nisso!",
            "Seja sempre você mesmo, a menos que você possa ser um unicórnio. Então, seja um unicórnio.",
            "Acredite no seu potencial, mesmo que ninguém mais acredite que ele exista.",
            "Lembre-se sempre: você é único, assim como todos os outros.",
            "Nunca subestime sua capacidade de encontrar problemas onde não existem.",
            "Você é tão organizado quanto um armário de roupas de um adolescente.",
            "A vida é cheia de obstáculos, mas você é um especialista em tropeçar neles.",
            "Seu otimismo é contagiante, assim como uma gripe no inverno.",
            "Continue assim, sua paciência é tão grande quanto um vídeo carregando na internet discada.",
            "Não se preocupe com os críticos, eles só estão com inveja da sua habilidade em ignorá-los.",
            "Lembre-se: os sonhos podem se tornar realidade, desde que sejam extremamente realistas.",
            "Você é tão bom em resolver problemas quanto uma girafa jogando basquete.",
            "Acredite em si mesmo, mesmo que ninguém mais acredite, porque precisamos de mais pessoas assim no mundo.",
            "Continue assim, suas habilidades multitarefas são tão boas quanto um peixe andando de bicicleta.",
            "Não se preocupe com os haters, eles só invejam a sua habilidade em procrastinar.",
            "Você é a prova viva de que a perfeição é superestimada.",
            "Não se preocupe em falhar, você é um especialista nisso!",
            "Seja sempre você mesmo, a menos que você possa ser um unicórnio. Então, seja um unicórnio.",
            "Acredite no seu potencial, mesmo que ninguém mais acredite que ele exista.",
            "Lembre-se sempre: você é único, assim como todos os outros.",
            "Nunca subestime sua capacidade de encontrar problemas onde não existem.",
            "Você é tão organizado quanto um armário de roupas de um adolescente.",
            "A vida é cheia de obstáculos, mas você é um especialista em tropeçar neles.",
            "Seu otimismo é contagiante, assim como uma gripe no inverno.",
            "Continue assim, sua paciência é tão grande quanto um vídeo carregando na internet discada.",
            "Não se preocupe com os críticos, eles só estão com inveja da sua habilidade em ignorá-los.",
            "Lembre-se: os sonhos podem se tornar realidade, desde que sejam extremamente realistas.",
            "Você é tão bom em resolver problemas quanto uma girafa jogando basquete.",
            "Acredite em si mesmo, mesmo que ninguém mais acredite, porque precisamos de mais pessoas assim no mundo.",
            "Continue assim, suas habilidades multitarefas são tão boas quanto um peixe andando de bicicleta.",
            "Não se preocupe com os haters, eles só invejam a sua habilidade em procrastinar.",
            "Você é a prova viva de que a perfeição é superestimada.",
            "Não se preocupe em falhar, você é um especialista nisso!",
            "Seja sempre você mesmo, a menos que você possa ser um unicórnio. Então, seja um unicórnio.",
            "Acredite no seu potencial, mesmo que ninguém mais acredite que ele exista.",
            "Lembre-se sempre: você é único, assim como todos os outros.",
            "Nunca subestime sua capacidade de encontrar problemas onde não existem.",
            "Você é tão organizado quanto um armário de roupas de um adolescente.",
            "A vida é cheia de obstáculos, mas você é um especialista em tropeçar neles.",
            "Seu otimismo é contagiante, assim como uma gripe no inverno.",
            "Continue assim, sua paciência é tão grande quanto um vídeo carregando na internet discada.",
            "Não se preocupe com os críticos, eles só estão com inveja da sua habilidade em ignorá-los.",
            "Lembre-se: os sonhos podem se tornar realidade, desde que sejam extremamente realistas.",
            "Você é tão bom em resolver problemas quanto uma girafa jogando basquete.",
            "Acredite em si mesmo, mesmo que ninguém mais acredite, porque precisamos de mais pessoas assim no mundo.",
            "Continue assim, suas habilidades multitarefas são tão boas quanto um peixe andando de bicicleta.",
            "Não se preocupe com os haters, eles só invejam a sua habilidade em procrastinar.",
            "Você é a prova viva de que a perfeição é superestimada.",
            "Não se preocupe em falhar, você é um especialista nisso!",
            "Seja sempre você mesmo, a menos que você possa ser um unicórnio. Então, seja um unicórnio.",
            "Acredite no seu potencial, mesmo que ninguém mais acredite que ele exista.",
            "Lembre-se sempre: você é único, assim como todos os outros.",
            "Nunca subestime sua capacidade de encontrar problemas onde não existem.",
            "Você é tão organizado quanto um armário de roupas de um adolescente.",
            "A vida é cheia de obstáculos, mas você é um especialista em tropeçar neles.",
            "Seu otimismo é contagiante, assim como uma gripe no inverno.",
            "Continue assim, sua paciência é tão grande quanto um vídeo carregando na internet discada.",
            "Não se preocupe com os críticos, eles só estão com inveja da sua habilidade em ignorá-los.",
            "Lembre-se: os sonhos podem se tornar realidade, desde que sejam extremamente realistas.",
            "Você é tão bom em resolver problemas quanto uma girafa jogando basquete.",
            "Acredite em si mesmo, mesmo que ninguém mais acredite, porque precisamos de mais pessoas assim no mundo.",
            "Continue assim, suas habilidades multitarefas são tão boas quanto um peixe andando de bicicleta.",
            "Não se preocupe com os haters, eles só invejam a sua habilidade em procrastinar.",
            "Você é a prova viva de que a perfeição é superestimada.",
            "Não se preocupe em falhar, você é um especialista nisso!",
            "Seja sempre você mesmo, a menos que você possa ser um unicórnio. Então, seja um unicórnio.",
            "Acredite no seu potencial, mesmo que ninguém mais acredite que ele exista.",
            "Lembre-se sempre: você é único, assim como todos os outros.",
            "Nunca subestime sua capacidade de encontrar problemas onde não existem.",
            "Você é tão organizado quanto um armário de roupas de um adolescente.",
            "A vida é cheia de obstáculos, mas você é um especialista em tropeçar neles.",
            "Seu otimismo é contagiante, assim como uma gripe no inverno.",
            "Continue assim, sua paciência é tão grande quanto um vídeo carregando na internet discada.",
            "Não se preocupe com os críticos, eles só estão com inveja da sua habilidade em ignorá-los.",
            "Lembre-se: os sonhos podem se tornar realidade, desde que sejam extremamente realistas.",
            "Você é tão bom em resolver problemas quanto uma girafa jogando basquete.",
            "Acredite em si mesmo, mesmo que ninguém mais acredite, porque precisamos de mais pessoas assim no mundo.",
            "Continue assim, suas habilidades multitarefas são tão boas quanto um peixe andando de bicicleta.",
            "Não se preocupe com os haters, eles só invejam a sua habilidade em procrastinar.",
            "Você é a prova viva de que a perfeição é superestimada.",
            "Não se preocupe em falhar, você é um especialista nisso!",
            "Seja sempre você mesmo, a menos que você possa ser um unicórnio. Então, seja um unicórnio.",
            "Acredite no seu potencial, mesmo que ninguém mais acredite que ele exista.",
            "Lembre-se sempre: você é único, assim como todos os outros.",
            "Nunca subestime sua capacidade de encontrar problemas onde não existem.",
            "Você é tão organizado quanto um armário de roupas de um adolescente.",
            "A vida é cheia de obstáculos, mas você é um especialista em tropeçar neles.",
            "Seu otimismo é contagiante, assim como uma gripe no inverno.",
            "Continue assim, sua paciência é tão grande quanto um vídeo carregando na internet discada.",
            "Não se preocupe com os críticos, eles só estão com inveja da sua habilidade em ignorá-los.",
            "Lembre-se: os sonhos podem se tornar realidade, desde que sejam extremamente realistas.",
            "Você é tão bom em resolver problemas quanto uma girafa jogando basquete.",
            "Acredite em si mesmo, mesmo que ninguém mais acredite, porque precisamos de mais pessoas assim no mundo.",
            "Continue assim, suas habilidades multitarefas são tão boas quanto um peixe andando de bicicleta.",
            "Não se preocupe com os haters, eles só invejam a sua habilidade em procrastinar.",
            "Você é a prova viva de que a perfeição é superestimada.",
            "Não se preocupe em falhar, você é um especialista nisso!",
            "Seja sempre você mesmo, a menos que você possa ser um unicórnio. Então, seja um unicórnio.",
            "Acredite no seu potencial, mesmo que ninguém mais acredite que ele exista.",
            "Lembre-se sempre: você é único, assim como todos os outros.",
            "Nunca subestime sua capacidade de encontrar problemas onde não existem.",
            "Você é tão organizado quanto um armário de roupas de um adolescente.",
            "A vida é cheia de obstáculos, mas você é um especialista em tropeçar neles.",
            "Seu otimismo é contagiante, assim como uma gripe no inverno.",
            "Continue assim, sua paciência é tão grande quanto um vídeo carregando na internet discada.",
            "Não se preocupe com os críticos, eles só estão com inveja da sua habilidade em ignorá-los.",
            "Lembre-se: os sonhos podem se tornar realidade, desde que sejam extremamente realistas.",
            "Você é tão bom em resolver problemas quanto uma girafa jogando basquete.",
            "Acredite em si mesmo, mesmo que ninguém mais acredite, porque precisamos de mais pessoas assim no mundo.",
            "Continue assim, suas habilidades multitarefas são tão boas quanto um peixe andando de bicicleta.",
            "Não se preocupe com os haters, eles só invejam a sua habilidade em procrastinar.",
            "Você é a prova viva de que a perfeição é superestimada.",
            "Não se preocupe em falhar, você é um especialista nisso!",
            "Seja sempre você mesmo, a menos que você possa ser um unicórnio. Então, seja um unicórnio.",
            "Acredite no seu potencial, mesmo que ninguém mais acredite que ele exista.",
            "Lembre-se sempre: você é único, assim como todos os outros.",
            "Nunca subestime sua capacidade de encontrar problemas onde não existem.",
            "Você é tão organizado quanto um armário de roupas de um adolescente.",
            "A vida é cheia de obstáculos, mas você é um especialista em tropeçar neles.",
            "Seu otimismo é contagiante, assim como uma gripe no inverno.",
            "Continue assim, sua paciência é tão grande quanto um vídeo carregando na internet discada.",
            "Não se preocupe com os críticos, eles só estão com inveja da sua habilidade em ignorá-los.",
            "Lembre-se: os sonhos podem se tornar realidade, desde que sejam extremamente realistas.",
            "Você é tão bom em resolver problemas quanto uma girafa jogando basquete.",
            "Acredite em si mesmo, mesmo que ninguém mais acredite, porque precisamos de mais pessoas assim no mundo.",
            "Continue assim, suas habilidades multitarefas são tão boas quanto um peixe andando de bicicleta.",
            "Não se preocupe com os haters, eles só invejam a sua habilidade em procrastinar.",
            "Você é a prova viva de que a perfeição é superestimada.",
            "Não se preocupe em falhar, você é um especialista nisso!",
            "Seja sempre você mesmo, a menos que você possa ser um unicórnio. Então, seja um unicórnio.",
            "Acredite no seu potencial, mesmo que ninguém mais acredite que ele exista.",
            "Lembre-se sempre: você é único, assim como todos os outros.",
            "Nunca subestime sua capacidade de encontrar problemas onde não existem.",
            "Você é tão organizado quanto um armário de roupas de um adolescente.",
            "A vida é cheia de obstáculos, mas você é um especialista em tropeçar neles.",
            "Seu otimismo é contagiante, assim como uma gripe no inverno.",
            "Continue assim, sua paciência é tão grande quanto um vídeo carregando na internet discada.",
            "Não se preocupe com os críticos, eles só estão com inveja da sua habilidade em ignorá-los.",
            "Lembre-se: os sonhos podem se tornar realidade, desde que sejam extremamente realistas.",
            "Você é tão bom em resolver problemas quanto uma girafa jogando basquete.",
            "Acredite em si mesmo, mesmo que ninguém mais acredite, porque precisamos de mais pessoas assim no mundo.",
            "Continue assim, suas habilidades multitarefas são tão boas quanto um peixe andando de bicicleta.",
            "Não se preocupe com os haters, eles só invejam a sua habilidade em procrastinar.",
            "Você é a prova viva de que a perfeição é superestimada.",
            "Não se preocupe em falhar, você é um especialista nisso!",
            "Seja sempre você mesmo, a menos que você possa ser um unicórnio. Então, seja um unicórnio.",
            "Acredite no seu potencial, mesmo que ninguém mais acredite que ele exista.",
            "Lembre-se sempre: você é único, assim como todos os outros.",
            "Nunca subestime sua capacidade de encontrar problemas onde não existem.",
            "Você é tão organizado quanto um armário de roupas de um adolescente.",
            "A vida é cheia de obstáculos, mas você é um especialista em tropeçar neles.",
            "Seu otimismo é contagiante, assim como uma gripe no inverno.",
            "Continue assim, sua paciência é tão grande quanto um vídeo carregando na internet discada.",
            "Não se preocupe com os críticos, eles só estão com inveja da sua habilidade em ignorá-los.",
            "Lembre-se: os sonhos podem se tornar realidade, desde que sejam extremamente realistas.",
            "Você é tão bom em resolver problemas quanto uma girafa jogando basquete.",
            "Acredite em si mesmo, mesmo que ninguém mais acredite, porque precisamos de mais pessoas assim no mundo.",
            "Continue assim, suas habilidades multitarefas são tão boas quanto um peixe andando de bicicleta.",
            "Não se preocupe com os haters, eles só invejam a sua habilidade em procrastinar.",
            "Você é a prova viva de que a perfeição é superestimada.",
            "Não se preocupe em falhar, você é um especialista nisso!",
            "Seja sempre você mesmo, a menos que você possa ser um unicórnio. Então, seja um unicórnio.",
            "Acredite no seu potencial, mesmo que ninguém mais acredite que ele exista.",
            "Lembre-se sempre: você é único, assim como todos os outros.",
            "Nunca subestime sua capacidade de encontrar problemas onde não existem.",
            "Você é tão organizado quanto um armário de roupas de um adolescente.",
            "A vida é cheia de obstáculos, mas você é um especialista em tropeçar neles.",
            "Seu otimismo é contagiante, assim como uma gripe no inverno.",
            "Continue assim, sua paciência é tão grande quanto um vídeo carregando na internet discada.",
            "Não se preocupe com os críticos, eles só estão com inveja da sua habilidade em ignorá-los.",
            "Lembre-se: os sonhos podem se tornar realidade, desde que sejam extremamente realistas.",
            "Você é tão bom em resolver problemas quanto uma girafa jogando basquete.",
            "Acredite em si mesmo, mesmo que ninguém mais acredite, porque precisamos de mais pessoas assim no mundo.",
            "Continue assim, suas habilidades multitarefas são tão boas quanto um peixe andando de bicicleta.",
            "Não se preocupe com os haters, eles só invejam a sua habilidade em procrastinar.",
            "Você é a prova viva de que a perfeição é superestimada.",
            "Não se preocupe em falhar, você é um especialista nisso!",
            "Seja sempre você mesmo, a menos que você possa ser um unicórnio. Então, seja um unicórnio.",
            "Acredite no seu potencial, mesmo que ninguém mais acredite que ele exista.",
            "Lembre-se sempre: você é único, assim como todos os outros.",
            "Nunca subestime sua capacidade de encontrar problemas onde não existem.",
            "Você é tão organizado quanto um armário de roupas de um adolescente.",
            "A vida é cheia de obstáculos, mas você é um especialista em tropeçar neles.",
            "Seu otimismo é contagiante, assim como uma gripe no inverno.",
            "Continue assim, sua paciência é tão grande quanto um vídeo carregando na internet discada.",
            "Não se preocupe com os críticos, eles só estão com inveja da sua habilidade em ignorá-los.",
            "Lembre-se: os sonhos podem se tornar realidade, desde que sejam extremamente realistas.",
            "Você é tão bom em resolver problemas quanto uma girafa jogando basquete.",
            "Acredite em si mesmo, mesmo que ninguém mais acredite, porque precisamos de mais pessoas assim no mundo.",
            "Continue assim, suas habilidades multitarefas são tão boas quanto um peixe andando de bicicleta.",
            "Não se preocupe com os haters, eles só invejam a sua habilidade em procrastinar.",
            "Você é a prova viva de que a perfeição é superestimada.",
            "Não se preocupe em falhar, você é um especialista nisso!",
            "Seja sempre você mesmo, a menos que você possa ser um unicórnio. Então, seja um unicórnio.",
            "Acredite no seu potencial, mesmo que ninguém mais acredite que ele exista.",
            "Lembre-se sempre: você é único, assim como todos os outros.",
            "Nunca subestime sua capacidade de encontrar problemas onde não existem.",
            "Você é tão organizado quanto um armário de roupas de um adolescente.",
            "A vida é cheia de obstáculos, mas você é um especialista em tropeçar neles.",
            "Seu otimismo é contagiante, assim como uma gripe no inverno.",
            "Continue assim, sua paciência é tão grande quanto um vídeo carregando na internet discada.",
            "Não se preocupe com os críticos, eles só estão com inveja da sua habilidade em ignorá-los.",
            "Lembre-se: os sonhos podem se tornar realidade, desde que sejam extremamente realistas.",
            "Você é tão bom em resolver problemas quanto uma girafa jogando basquete.",
            "Acredite em si mesmo, mesmo que ninguém mais acredite, porque precisamos de mais pessoas assim no mundo.",
            "Continue assim, suas habilidades multitarefas são tão boas quanto um peixe andando de bicicleta.",
            "Não se preocupe com os haters, eles só invejam a sua habilidade em procrastinar.",
            "Você é a prova viva de que a perfeição é superestimada.",
            "Não se preocupe em falhar, você é um especialista nisso!",
            "Seja sempre você mesmo, a menos que você possa ser um unicórnio. Então, seja um unicórnio.",
            "Acredite no seu potencial, mesmo que ninguém mais acredite que ele exista.",
            "Lembre-se sempre: você é único, assim como todos os outros.",
            "Nunca subestime sua capacidade de encontrar problemas onde não existem.",
            "Você é tão organizado quanto um armário de roupas de um adolescente.",
            "A vida é cheia de obstáculos, mas você é um especialista em tropeçar neles.",
            "Seu otimismo é contagiante, assim como uma gripe no inverno.",
            "Continue assim, sua paciência é tão grande quanto um vídeo carregando na internet discada.",
            "Não se preocupe com os críticos, eles só estão com inveja da sua habilidade em ignorá-los.",
            "Lembre-se: os sonhos podem se tornar realidade, desde que sejam extremamente realistas.",
            "Você é tão bom em resolver problemas quanto uma girafa jogando basquete.",
            "Acredite em si mesmo, mesmo que ninguém mais acredite, porque precisamos de mais pessoas assim no mundo.",
            "Continue assim, suas habilidades multitarefas são tão boas quanto um peixe andando de bicicleta.",
            "Não se preocupe com os haters, eles só invejam a sua habilidade em procrastinar.",
            "Você é a prova viva de que a perfeição é superestimada.",
            "Não se preocupe em falhar, você é um especialista nisso!",
            "Seja sempre você mesmo, a menos que você possa ser um unicórnio. Então, seja um unicórnio.",
            "Acredite no seu potencial, mesmo que ninguém mais acredite que ele exista.",
            "Lembre-se sempre: você é único, assim como todos os outros.",
            "Nunca subestime sua capacidade de encontrar problemas onde não existem.",
            "Você é tão organizado quanto um armário de roupas de um adolescente.",
            "A vida é cheia de obstáculos, mas você é um especialista em tropeçar neles.",
            "Seu otimismo é contagiante, assim como uma gripe no inverno.",
            "Continue assim, sua paciência é tão grande quanto um vídeo carregando na internet discada.",
            "Não se preocupe com os críticos, eles só estão com inveja da sua habilidade em ignorá-los.",
            "Lembre-se: os sonhos podem se tornar realidade, desde que sejam extremamente realistas.",
            "Você é tão bom em resolver problemas quanto uma girafa jogando basquete.",
            "Acredite em si mesmo, mesmo que ninguém mais acredite, porque precisamos de mais pessoas assim no mundo.",
            "Continue assim, suas habilidades multitarefas são tão boas quanto um peixe andando de bicicleta.",
            "Não se preocupe com os haters, eles só invejam a sua habilidade em procrastinar.",
            "Você é a prova viva de que a perfeição é superestimada.",
            "Não se preocupe em falhar, você é um especialista nisso!",
            "Seja sempre você mesmo, a menos que você possa ser um unicórnio. Então, seja um unicórnio.",
            "Acredite no seu potencial, mesmo que ninguém mais acredite que ele exista.",
            "Lembre-se sempre: você é único, assim como todos os outros.",
            "Nunca subestime sua capacidade de encontrar problemas onde não existem.",
            "Você é tão organizado quanto um armário de roupas de um adolescente.",
            "A vida é cheia de obstáculos, mas você é um especialista em tropeçar neles.",
            "Seu otimismo é contagiante, assim como uma gripe no inverno.",
            "Continue assim, sua paciência é tão grande quanto um vídeo carregando na internet discada.",
            "Não se preocupe com os críticos, eles só estão com inveja da sua habilidade em ignorá-los.",
            "Lembre-se: os sonhos podem se tornar realidade, desde que sejam extremamente realistas.",
            "Você é tão bom em resolver problemas quanto uma girafa jogando basquete.",
            "Acredite em si mesmo, mesmo que ninguém mais acredite, porque precisamos de mais pessoas assim no mundo.",
            "Continue assim, suas habilidades multitarefas são tão boas quanto um peixe andando de bicicleta.",
            "Não se preocupe com os haters, eles só invejam a sua habilidade em procrastinar.",
            "Você é a prova viva de que a perfeição é superestimada.",
            "Não se preocupe em falhar, você é um especialista nisso!",
            "Seja sempre você mesmo, a menos que você possa ser um unicórnio. Então, seja um unicórnio.",
            "Acredite no seu potencial, mesmo que ninguém mais acredite que ele exista.",
            "Lembre-se sempre: você é único, assim como todos os outros.",
            "Nunca subestime sua capacidade de encontrar problemas onde não existem.",
            "Você é tão organizado quanto um armário de roupas de um adolescente.",
            "A vida é cheia de obstáculos, mas você é um especialista em tropeçar neles.",
            "Seu otimismo é contagiante, assim como uma gripe no inverno.",
            "Continue assim, sua paciência é tão grande quanto um vídeo carregando na internet discada.",
            "Não se preocupe com os críticos, eles só estão com inveja da sua habilidade em ignorá-los.",
            "Lembre-se: os sonhos podem se tornar realidade, desde que sejam extremamente realistas.",
            "Você é tão bom em resolver problemas quanto uma girafa jogando basquete.",
            "Acredite em si mesmo, mesmo que ninguém mais acredite, porque precisamos de mais pessoas assim no mundo.",
            "Continue assim, suas habilidades multitarefas são tão boas quanto um peixe andando de bicicleta.",
            "Não se preocupe com os haters, eles só invejam a sua habilidade em procrastinar.",
            "Você é a prova viva de que a perfeição é superestimada.",
            "Não se preocupe em falhar, você é um especialista nisso!",
            "Seja sempre você mesmo, a menos que você possa ser um unicórnio. Então, seja um unicórnio.",
            "Acredite no seu potencial, mesmo que ninguém mais acredite que ele exista.",
            "Lembre-se sempre: você é único, assim como todos os outros.",
            "Nunca subestime sua capacidade de encontrar problemas onde não existem.",
            "Você é tão organizado quanto um armário de roupas de um adolescente.",
            "A vida é cheia de obstáculos, mas você é um especialista em tropeçar neles.",
            "Seu otimismo é contagiante, assim como uma gripe no inverno.",
            "Continue assim, sua paciência é tão grande quanto um vídeo carregando na internet discada.",
            "Não se preocupe com os críticos, eles só estão com inveja da sua habilidade em ignorá-los.",
            "Lembre-se: os sonhos podem se tornar realidade, desde que sejam extremamente realistas.",
            "Você é tão bom em resolver problemas quanto uma girafa jogando basquete.",
            "Acredite em si mesmo, mesmo que ninguém mais acredite, porque precisamos de mais pessoas assim no mundo.",
            "Continue assim, suas habilidades multitarefas são tão boas quanto um peixe andando de bicicleta.",
            "Não se preocupe com os haters, eles só invejam a sua habilidade em procrastinar.",
            "Você é a prova viva de que a perfeição é superestimada.",
            "Não se preocupe em falhar, você é um especialista nisso!",
            "Seja sempre você mesmo, a menos que você possa ser um unicórnio. Então, seja um unicórnio.",
            "Acredite no seu potencial, mesmo que ninguém mais acredite que ele exista.",
            "Lembre-se sempre: você é único, assim como todos os outros.",
            "Nunca subestime sua capacidade de encontrar problemas onde não existem.",
            "Você é tão organizado quanto um armário de roupas de um adolescente.",
            "A vida é cheia de obstáculos, mas você é um especialista em tropeçar neles.",
            "Seu otimismo é contagiante, assim como uma gripe no inverno.",
            "Continue assim, sua paciência é tão grande quanto um vídeo carregando na internet discada.",
            "Não se preocupe com os críticos, eles só estão com inveja da sua habilidade em ignorá-los.",
            "Lembre-se: os sonhos podem se tornar realidade, desde que sejam extremamente realistas.",
            "Você é tão bom em resolver problemas quanto uma girafa jogando basquete.",
            "Acredite em si mesmo, mesmo que ninguém mais acredite, porque precisamos de mais pessoas assim no mundo.",
            "Continue assim, suas habilidades multitarefas são tão boas quanto um peixe andando de bicicleta.",
            "Não se preocupe com os haters, eles só invejam a sua habilidade em procrastinar.",
            "Você é a prova viva de que a perfeição é superestimada.",
            "Não se preocupe em falhar, você é um especialista nisso!",
            "Seja sempre você mesmo, a menos que você possa ser um unicórnio. Então, seja um unicórnio.",
            "Acredite no seu potencial, mesmo que ninguém mais acredite que ele exista.",
            "Lembre-se sempre: você é único, assim como todos os outros.",
            "Nunca subestime sua capacidade de encontrar problemas onde não existem.",
            "Você é tão organizado quanto um armário de roupas de um adolescente.",
            "A vida é cheia de obstáculos, mas você é um especialista em tropeçar neles.",
            "Seu otimismo é contagiante, assim como uma gripe no inverno.",
            "Continue assim, sua paciência é tão grande quanto um vídeo carregando na internet discada.",
            "Não se preocupe com os críticos, eles só estão com inveja da sua habilidade em ignorá-los.",
            "Lembre-se: os sonhos podem se tornar realidade, desde que sejam extremamente realistas.",
            "Você é tão bom em resolver problemas quanto uma girafa jogando basquete.",
            "Acredite em si mesmo, mesmo que ninguém mais acredite, porque precisamos de mais pessoas assim no mundo.",
            "Continue assim, suas habilidades multitarefas são tão boas quanto um peixe andando de bicicleta.",
            "Não se preocupe com os haters, eles só invejam a sua habilidade em procrastinar.",
            "Você é a prova viva de que a perfeição é superestimada.",
            "Não se preocupe em falhar, você é um especialista nisso!",
            "Seja sempre você mesmo, a menos que você possa ser um unicórnio. Então, seja um unicórnio.",
            "Acredite no seu potencial, mesmo que ninguém mais acredite que ele exista.",
            "Lembre-se sempre: você é único, assim como todos os outros.",
            "Nunca subestime sua capacidade de encontrar problemas onde não existem.",
            "Você é tão organizado quanto um armário de roupas de um adolescente.",
            "A vida é cheia de obstáculos, mas você é um especialista em tropeçar neles.",
            "Seu otimismo é contagiante, assim como uma gripe no inverno.",
            "Continue assim, sua paciência é tão grande quanto um vídeo carregando na internet discada.",
            "Não se preocupe com os críticos, eles só estão com inveja da sua habilidade em ignorá-los.",
            "Lembre-se: os sonhos podem se tornar realidade, desde que sejam extremamente realistas.",
            "Você é tão bom em resolver problemas quanto uma girafa jogando basquete.",
            "Acredite em si mesmo, mesmo que ninguém mais acredite, porque precisamos de mais pessoas assim no mundo.",
            "Continue assim, suas habilidades multitarefas são tão boas quanto um peixe andando de bicicleta.",
            "Não se preocupe com os haters, eles só invejam a sua habilidade em procrastinar.",
            "Você é a prova viva de que a perfeição é superestimada.",
            "Não se preocupe em falhar, você é um especialista nisso!",
            "Seja sempre você mesmo, a menos que você possa ser um unicórnio. Então, seja um unicórnio.",
            "Acredite no seu potencial, mesmo que ninguém mais acredite que ele exista.",
            "Lembre-se sempre: você é único, assim como todos os outros.",
            "Nunca subestime sua capacidade de encontrar problemas onde não existem.",
            "Você é tão organizado quanto um armário de roupas de um adolescente.",
            "A vida é cheia de obstáculos, mas você é um especialista em tropeçar neles.",
            "Seu otimismo é contagiante, assim como uma gripe no inverno.",
            "Continue assim, sua paciência é tão grande quanto um vídeo carregando na internet discada.",
            "Não se preocupe com os críticos, eles só estão com inveja da sua habilidade em ignorá-los.",
            "Lembre-se: os sonhos podem se tornar realidade, desde que sejam extremamente realistas.",
            "Você é tão bom em resolver problemas quanto uma girafa jogando basquete.",
            "Acredite em si mesmo, mesmo que ninguém mais acredite, porque precisamos de mais pessoas assim no mundo.",
            "Continue assim, suas habilidades multitarefas são tão boas quanto um peixe andando de bicicleta.",
            "Não se preocupe com os haters, eles só invejam a sua habilidade em procrastinar.",
            "Você é a prova viva de que a perfeição é superestimada.",
            "Não se preocupe em falhar, você é um especialista nisso!",
            "Seja sempre você mesmo, a menos que você possa ser um unicórnio. Então, seja um unicórnio.",
            "Acredite no seu potencial, mesmo que ninguém mais acredite que ele exista.",
            "Lembre-se sempre: você é único, assim como todos os outros.",
            "Nunca subestime sua capacidade de encontrar problemas onde não existem.",
            "Você é tão organizado quanto um armário de roupas de um adolescente.",
            "A vida é cheia de obstáculos, mas você é um especialista em tropeçar neles.",
            "Seu otimismo é contagiante, assim como uma gripe no inverno.",
            "Continue assim, sua paciência é tão grande quanto um vídeo carregando na internet discada.",
            "Não se preocupe com os críticos, eles só estão com inveja da sua habilidade em ignorá-los.",
            "Lembre-se: os sonhos podem se tornar realidade, desde que sejam extremamente realistas.",
            "Você é tão bom em resolver problemas quanto uma girafa jogando basquete.",
            "Acredite em si mesmo, mesmo que ninguém mais acredite, porque precisamos de mais pessoas assim no mundo.",
            "Continue assim, suas habilidades multitarefas são tão boas quanto um peixe andando de bicicleta.",
            "Não se preocupe com os haters, eles só invejam a sua habilidade em procrastinar.",
            "Você é a prova viva de que a perfeição é superestimada.",
            "Não se preocupe em falhar, você é um especialista nisso!",
            "Seja sempre você mesmo, a menos que você possa ser um unicórnio. Então, seja um unicórnio.",
            "Acredite no seu potencial, mesmo que ninguém mais acredite que ele exista.",
            "Lembre-se sempre: você é único, assim como todos os outros.",
            "Nunca subestime sua capacidade de encontrar problemas onde não existem.",
            "Você é tão organizado quanto um armário de roupas de um adolescente.",
            "A vida é cheia de obstáculos, mas você é um especialista em tropeçar neles.",
            "Seu otimismo é contagiante, assim como uma gripe no inverno.",
            "Continue assim, sua paciência é tão grande quanto um vídeo carregando na internet discada.",
            "Não se preocupe com os críticos, eles só estão com inveja da sua habilidade em ignorá-los.",
            "Lembre-se: os sonhos podem se tornar realidade, desde que sejam extremamente realistas.",
            "Você é tão bom em resolver problemas quanto uma girafa jogando basquete.",
            "Acredite em si mesmo, mesmo que ninguém mais acredite, porque precisamos de mais pessoas assim no mundo.",
            "Continue assim, suas habilidades multitarefas são tão boas quanto um peixe andando de bicicleta.",
            "Não se preocupe com os haters, eles só invejam a sua habilidade em procrastinar.",
            "Você é a prova viva de que a perfeição é superestimada.",
            "Não se preocupe em falhar, você é um especialista nisso!",
            "Seja sempre você mesmo, a menos que você possa ser um unicórnio. Então, seja um unicórnio.",
            "Acredite no seu potencial, mesmo que ninguém mais acredite que ele exista.",
            "Lembre-se sempre: você é único, assim como todos os outros.",
            "Nunca subestime sua capacidade de encontrar problemas onde não existem.",
            "Você é tão organizado quanto um armário de roupas de um adolescente.",
            "A vida é cheia de obstáculos, mas você é um especialista em tropeçar neles.",
            "Seu otimismo é contagiante, assim como uma gripe no inverno.",
            "Continue assim, sua paciência é tão grande quanto um vídeo carregando na internet discada.",
            "Não se preocupe com os críticos, eles só estão com inveja da sua habilidade em ignorá-los.",
            "Lembre-se: os sonhos podem se tornar realidade, desde que sejam extremamente realistas.",
            "Você é tão bom em resolver problemas quanto uma girafa jogando basquete.",
            "Acredite em si mesmo, mesmo que ninguém mais acredite, porque precisamos de mais pessoas assim no mundo.",
            "Continue assim, suas habilidades multitarefas são tão boas quanto um peixe andando de bicicleta.",
            "Não se preocupe com os haters, eles só invejam a sua habilidade em procrastinar.",
            "Você é a prova viva de que a perfeição é superestimada.",
            "Não se preocupe em falhar, você é um especialista nisso!",
            "Seja sempre você mesmo, a menos que você possa ser um unicórnio. Então, seja um unicórnio.",
            "Acredite no seu potencial, mesmo que ninguém mais acredite que ele exista.",
            "Lembre-se sempre: você é único, assim como todos os outros.",
            "Nunca subestime sua capacidade de encontrar problemas onde não existem.",
            "Você é tão organizado quanto um armário de roupas de um adolescente.",
            "A vida é cheia de obstáculos, mas você é um especialista em tropeçar neles.",
            "Seu otimismo é contagiante, assim como uma gripe no inverno.",
            "Continue assim, sua paciência é tão grande quanto um vídeo carregando na internet discada.",
            "Não se preocupe com os críticos, eles só estão com inveja da sua habilidade em ignorá-los.",
            "Lembre-se: os sonhos podem se tornar realidade, desde que sejam extremamente realistas.",
            "Você é tão bom em resolver problemas quanto uma girafa jogando basquete.",
            "Acredite em si mesmo, mesmo que ninguém mais acredite, porque precisamos de mais pessoas assim no mundo.",
            "Continue assim, suas habilidades multitarefas são tão boas quanto um peixe andando de bicicleta.",
            "Não se preocupe com os haters, eles só invejam a sua habilidade em procrastinar.",
            "Você é a prova viva de que a perfeição é superestimada.",
            "Não se preocupe em falhar, você é um especialista nisso!",
            "Seja sempre você mesmo, a menos que você possa ser um unicórnio. Então, seja um unicórnio.",
            "Acredite no seu potencial, mesmo que ninguém mais acredite que ele exista.",
            "Lembre-se sempre: você é único, assim como todos os outros.",
            "Nunca subestime sua capacidade de encontrar problemas onde não existem.",
            "Você é tão organizado quanto um armário de roupas de um adolescente.",
            "A vida é cheia de obstáculos, mas você é um especialista em tropeçar neles.",
            "Seu otimismo é contagiante, assim como uma gripe no inverno.",
            "Continue assim, sua paciência é tão grande quanto um vídeo carregando na internet discada.",
            "Não se preocupe com os críticos, eles só estão com inveja da sua habilidade em ignorá-los.",
            "Lembre-se: os sonhos podem se tornar realidade, desde que sejam extremamente realistas.",
            "Você é tão bom em resolver problemas quanto uma girafa jogando basquete.",
            "Acredite em si mesmo, mesmo que ninguém mais acredite, porque precisamos de mais pessoas assim no mundo.",
            "Continue assim, suas habilidades multitarefas são tão boas quanto um peixe andando de bicicleta.",
            "Não se preocupe com os haters, eles só invejam a sua habilidade em procrastinar.",
            "Você é a prova viva de que a perfeição é superestimada.",
            "Não se preocupe em falhar, você é um especialista nisso!",
            "Seja sempre você mesmo, a menos que você possa ser um unicórnio. Então, seja um unicórnio.",
            "Acredite no seu potencial, mesmo que ninguém mais acredite que ele exista.",
            "Lembre-se sempre: você é único, assim como todos os outros.",
            "Nunca subestime sua capacidade de encontrar problemas onde não existem.",
            "Você é tão organizado quanto um armário de roupas de um adolescente.",
            "A vida é cheia de obstáculos, mas você é um especialista em tropeçar neles.",
            "Seu otimismo é contagiante, assim como uma gripe no inverno.",
            "Continue assim, sua paciência é tão grande quanto um vídeo carregando na internet discada.",
            "Não se preocupe com os críticos, eles só estão com inveja da sua habilidade em ignorá-los.",
            "Lembre-se: os sonhos podem se tornar realidade, desde que sejam extremamente realistas.",
            "Você é tão bom em resolver problemas quanto uma girafa jogando basquete.",
            "Acredite em si mesmo, mesmo que ninguém mais acredite, porque precisamos de mais pessoas assim no mundo.",
            "Continue assim, suas habilidades multitarefas são tão boas quanto um peixe andando de bicicleta.",
            "Não se preocupe com os haters, eles só invejam a sua habilidade em procrastinar.",
            "Você é a prova viva de que a perfeição é superestimada.",
            "Não se preocupe em falhar, você é um especialista nisso!",
            "Seja sempre você mesmo, a menos que você possa ser um unicórnio. Então, seja um unicórnio.",
            "Acredite no seu potencial, mesmo que ninguém mais acredite que ele exista.",
            "Lembre-se sempre: você é único, assim como todos os outros.",
            "Nunca subestime sua capacidade de encontrar problemas onde não existem.",
            "Você é tão organizado quanto um armário de roupas de um adolescente.",
            "A vida é cheia de obstáculos, mas você é um especialista em tropeçar neles.",
            "Seu otimismo é contagiante, assim como uma gripe no inverno.",
            "Continue assim, sua paciência é tão grande quanto um vídeo carregando na internet discada.",
            "Não se preocupe com os críticos, eles só estão com inveja da sua habilidade em ignorá-los.",
            "Lembre-se: os sonhos podem se tornar realidade, desde que sejam extremamente realistas.",
            "Você é tão bom em resolver problemas quanto uma girafa jogando basquete.",
            "Acredite em si mesmo, mesmo que ninguém mais acredite, porque precisamos de mais pessoas assim no mundo.",
            "Continue assim, suas habilidades multitarefas são tão boas quanto um peixe andando de bicicleta.",
            "Não se preocupe com os haters, eles só invejam a sua habilidade em procrastinar.",
            "Você é a prova viva de que a perfeição é superestimada.",
            "Não se preocupe em falhar, você é um especialista nisso!",
            "Seja sempre você mesmo, a menos que você possa ser um unicórnio. Então, seja um unicórnio.",
            "Acredite no seu potencial, mesmo que ninguém mais acredite que ele exista.",
            "Lembre-se sempre: você é único, assim como todos os outros.",
            "Nunca subestime sua capacidade de encontrar problemas onde não existem.",
            "Você é tão organizado quanto um armário de roupas de um adolescente.",
            "A vida é cheia de obstáculos, mas você é um especialista em tropeçar neles.",
            "Seu otimismo é contagiante, assim como uma gripe no inverno.",
            "Continue assim, sua paciência é tão grande quanto um vídeo carregando na internet discada.",
            "Não se preocupe com os críticos, eles só estão com inveja da sua habilidade em ignorá-los.",
            "Lembre-se: os sonhos podem se tornar realidade, desde que sejam extremamente realistas.",
            "Você é tão bom em resolver problemas quanto uma girafa jogando basquete.",
            "Acredite em si mesmo, mesmo que ninguém mais acredite, porque precisamos de mais pessoas assim no mundo.",
            "Continue assim, suas habilidades multitarefas são tão boas quanto um peixe andando de bicicleta.",
            "Não se preocupe com os haters, eles só invejam a sua habilidade em procrastinar.",
            "Você é a prova viva de que a perfeição é superestimada.",
            "Não se preocupe em falhar, você é um especialista nisso!",
            "Seja sempre você mesmo, a menos que você possa ser um unicórnio. Então, seja um unicórnio.",
            "Acredite no seu potencial, mesmo que ninguém mais acredite que ele exista.",
            "Lembre-se sempre: você é único, assim como todos os outros.",
            "Nunca subestime sua capacidade de encontrar problemas onde não existem.",
            "Você é tão organizado quanto um armário de roupas de um adolescente.",
            "A vida é cheia de obstáculos, mas você é um especialista em tropeçar neles.",
            "Seu otimismo é contagiante, assim como uma gripe no inverno.",
            "Continue assim, sua paciência é tão grande quanto um vídeo carregando na internet discada.",
            "Não se preocupe com os críticos, eles só estão com inveja da sua habilidade em ignorá-los.",
            "Lembre-se: os sonhos podem se tornar realidade, desde que sejam extremamente realistas.",
            "Você é tão bom em resolver problemas quanto uma girafa jogando basquete.",
            "Acredite em si mesmo, mesmo que ninguém mais acredite, porque precisamos de mais pessoas assim no mundo.",
            "Continue assim, suas habilidades multitarefas são tão boas quanto um peixe andando de bicicleta.",
            "Não se preocupe com os haters, eles só invejam a sua habilidade em procrastinar.",
            "Você é a prova viva de que a perfeição é superestimada.",
            "Não se preocupe em falhar, você é um especialista nisso!",
            "Seja sempre você mesmo, a menos que você possa ser um unicórnio. Então, seja um unicórnio.",
            "Acredite em si mesmo, você é capaz de grandes conquistas.",
            "Seja a mudança que você deseja ver no mundo.",
            "A persistência é o caminho do êxito.",
            "Nada é impossível para aquele que persiste.",
            "A cada novo dia, novas oportunidades surgem.",
            "Não tenha medo de tentar algo novo.",
            "O sucesso vem para aqueles que não desistem.",
            "A vida é curta, aproveite cada momento.",
            "Acredite no seu potencial e vá em frente.",
            "Você é capaz de superar qualquer desafio.",
            "O otimismo é a chave para alcançar seus objetivos.",
            "Cada passo é importante para alcançar seus sonhos.",
            "Nunca é tarde para recomeçar e fazer diferente.",
            "Acredite na sua capacidade de vencer.",
            "A gratidão transforma sua vida.",
            "A persistência é a chave para alcançar o sucesso.",
            "A vida é uma jornada de aprendizado.",
            "Você é mais forte do que imagina.",
            "Enfrente seus medos e alcance suas metas.",
            "O sucesso começa com acreditar em si mesmo.",
            "Acredite em você, e os outros também acreditarão.",
            "Seja a melhor versão de si mesmo todos os dias.",
            "Sorria, isso pode mudar o dia de alguém.",
            "Não deixe que o medo te impeça de seguir em frente.",
            "Acredite no seu potencial e vá atrás dos seus sonhos.",
            "O sucesso é a soma de pequenos esforços repetidos diariamente.",
            "Você é capaz de conquistar tudo o que deseja.",
            "Acredite que você pode, e você já está no meio do caminho.",
            "A cada dia, você está mais próximo do seu objetivo.",
            "Supere os obstáculos com confiança e determinação.",
            "A vida é cheia de possibilidades, basta agarrá-las.",
            "Você é único e tem muito a oferecer ao mundo.",
            "Acredite, você é capaz de realizar coisas incríveis.",
            "A felicidade está nas pequenas coisas da vida.",
            "Seja grato pelo que tem e celebre suas conquistas.",
            "Confie no processo e no seu próprio tempo.",
            "Você é a soma das suas escolhas.",
            "Acredite na sua capacidade de transformar desafios em oportunidades.",
            "Cada dia é uma nova chance para fazer a diferença.",
            "Acredite em si mesmo e siga em frente sem olhar para trás.",
            "Você é capaz de enfrentar qualquer desafio que surgir.",
            "O poder está dentro de você, é só acreditar.",
            "Acredite no seu potencial e vá além dos seus limites.",
            "Nunca é tarde para correr atrás dos seus sonhos.",
            "Você é o autor da sua própria história.",
            "Acredite na sua força interior e conquiste o mundo.",
            "A felicidade começa quando você se valoriza.",
            "Você pode alcançar o que quiser, basta acreditar.",
            "Acredite no seu talento e mostre ao mundo o que você é capaz.",
            "Acredite em você mesmo e nada será impossível.",
            "Cada dia é uma oportunidade de recomeçar.",
            "Acredite na sua capacidade de superar qualquer desafio.",
            "Acredite que você pode e você está no meio do caminho.",
            "Acredite em si mesmo e transforme seus sonhos em realidade.",
            "Você é único, valorize-se.",
            "Acredite nas suas habilidades e alcance o sucesso.",
            "Acredite que você é capaz e você será.",
            "Acredite, você é mais forte do que imagina.",
            "Confie em você e supere todos os obstáculos.",
            "Acredite no seu potencial e faça acontecer.",
            "Acredite que cada dia é uma nova oportunidade de ser feliz.",
            "Você é capaz de alcançar seus objetivos, basta acreditar.",
            "Acredite em você mesmo e não tenha medo de brilhar.",
            "Acredite na sua capacidade de transformar seus sonhos em realidade.",
            "Você é capaz de fazer a diferença no mundo.",
            "Acredite no poder da sua mente e conquiste seus objetivos.",
            "Acredite na sua capacidade de superar desafios.",
            "Acredite que você é capaz de alcançar seus sonhos.",
            "Confie em você mesmo e vá atrás dos seus objetivos.",
            "Acredite no seu potencial e vá em busca dos seus sonhos.",
            "Acredite em si mesmo e seja a mudança que você deseja ver.",
            "Você é capaz de enfrentar qualquer desafio com coragem e determinação.",
            "Acredite em você e não tenha medo de arriscar.",
            "Acredite que cada dia é uma nova oportunidade para ser feliz.",
            "Confie no seu potencial e alcance seus objetivos.",
            "Acredite que você é capaz de vencer qualquer obstáculo.",
            "Você é capaz de realizar coisas incríveis, basta acreditar.",
            "Acredite que cada desafio é uma oportunidade de crescimento.",
            "Confie em você mesmo e siga em frente sem olhar para trás.",
            "Acredite no seu potencial e vá além dos seus limites.",
            "Você é único e tem muito a oferecer ao mundo.",
            "Acredite em si mesmo e nunca desista dos seus sonhos.",
            "Confie na sua intuição e siga o seu coração.",
            "Acredite em você e no seu potencial para alcançar seus objetivos.",
            "Você é capaz de realizar seus sonhos, basta acreditar.",
            "Acredite na sua capacidade de superar qualquer desafio.",
            "Confie em você mesmo e conquiste o que deseja.",
            "Acredite que você é capaz de alcançar seus objetivos.",
            "Acredite no seu potencial e supere seus limites.",
            "Confie em você e não tenha medo de arriscar.",
            "Acredite que cada dia é uma nova chance de ser feliz.",
            "Você é capaz de alcançar o sucesso, basta acreditar.",
            "Acredite em si mesmo e transforme seus sonhos em realidade.",
            "Confie na sua força interior e supere qualquer desafio.",
            "Acredite que você pode e você já está no meio do caminho.",
            "Você é único, valorize-se.",
            "Acredite nas suas habilidades e conquiste o que deseja.",
            "Acredite em você mesmo e seja a mudança que deseja ver.",
            "Confie em você e no seu potencial para realizar seus sonhos.",
            "Acredite que cada dia é uma oportunidade de recomeçar.",
            "Você é capaz de vencer qualquer obstáculo, basta acreditar.",
            "Acredite no poder da sua mente e alcance seus objetivos.",
            "Acredite em si mesmo e não desista dos seus sonhos.",
            "Confie em você e supere todas as dificuldades.",
            "Acredite que cada desafio é uma oportunidade de crescimento.",
            "Você é capaz de realizar seus sonhos, acredite.",
            "Acredite no seu potencial e vá em busca dos seus objetivos.",
            "Acredite em si mesmo e seja a melhor versão de você.",
            "Confie na sua capacidade de vencer e conquiste seus objetivos.",
            "Acredite que cada dia é uma nova chance de fazer acontecer.",
            "Você é único e tem o poder de transformar sua vida.",
            "Acredite em você e no seu potencial para alcançar seus sonhos.",
            "Acredite no seu talento e mostre ao mundo o que você é capaz.",
            "Confie em você e no processo da vida.",
            "Acredite que você é capaz de superar qualquer desafio.",
            "Acredite no seu potencial e conquiste seus objetivos.",
            "Você é capaz de realizar coisas incríveis, basta acreditar.",
            "Acredite que cada dia é uma nova oportunidade para ser feliz.",
            "Confie em você mesmo e vá atrás dos seus objetivos.",
            "Acredite no seu potencial e vá em busca dos seus sonhos.",
            "Acredite em si mesmo e seja a mudança que você deseja ver.",
            "Você é capaz de enfrentar qualquer desafio com coragem e determinação.",
            "Acredite em você e não tenha medo de arriscar.",
            "Acredite que cada desafio é uma oportunidade de crescimento.",
            "Confie em você mesmo e siga em frente sem olhar para trás.",
            "Acredite no seu potencial e vá além dos seus limites.",
            "Você é único e tem muito a oferecer ao mundo.",
            "Acredite em si mesmo e nunca desista dos seus sonhos.",
            "Confie na sua intuição e siga o seu coração.",
            "Acredite em você e no seu potencial para alcançar seus objetivos.",
            "Você é capaz de realizar seus sonhos, basta acreditar.",
            "Acredite na sua capacidade de superar qualquer desafio.",
            "Confie em você mesmo e conquiste o que deseja.",
            "Acredite que você é capaz de alcançar seus objetivos.",
            "Acredite no seu potencial e supere seus limites.",
            "Confie em você e não tenha medo de arriscar.",
            "Acredite que cada dia é uma nova chance de ser feliz.",
            "Você é capaz de alcançar o sucesso, basta acreditar.",
            "Acredite em si mesmo e transforme seus sonhos em realidade.",
            "Confie na sua força interior e supere qualquer desafio.",
            "Acredite que você pode e você já está no meio do caminho.",
            "Você é único, valorize-se.",
            "Acredite nas suas habilidades e conquiste o que deseja.",
            "Acredite em você mesmo e seja a mudança que deseja ver.",
            "Confie em você e no seu potencial para realizar seus sonhos.",
            "Acredite que cada dia é uma oportunidade de recomeçar.",
            "Você é capaz de vencer qualquer obstáculo, basta acreditar.",
            "Acredite no poder da sua mente e alcance seus objetivos.",
            "Acredite em si mesmo e não desista dos seus sonhos.",
            "Confie em você e supere todas as dificuldades.",
            "Acredite que cada desafio é uma oportunidade de crescimento.",
            "Você é capaz de realizar seus sonhos, acredite.",
            "Acredite no seu potencial e vá em busca dos seus objetivos.",
            "Acredite em si mesmo e seja a melhor versão de você.",
            "Confie na sua capacidade de vencer e conquiste seus objetivos.",
            "Acredite que cada dia é uma nova chance de fazer acontecer.",
            "Você é único e tem o poder de transformar sua vida.",
            "Acredite em você e no seu potencial para alcançar seus sonhos.",
            "Acredite no seu talento e mostre ao mundo o que você é capaz.",
            "Confie em você e no processo da vida.",
            "Acredite que você é capaz de superar qualquer desafio."};

    public String[] getMotivacionalMensagens() {
        return MOTIVACIONAL_MENSAGENS;
    }
}
